-- =============================================================================
-- 005_update_seed_accounts.sql
-- Updates existing seed accounts with new schema fields (title, simplified roles)
-- =============================================================================

-- Update profiles with title and ensure correct role mappings
-- The employee_id will be auto-generated by the trigger

DO $$
DECLARE
    v_super_admin_id UUID := '11111111-1111-1111-1111-111111111111';
    v_center_head_id UUID := '22222222-2222-2222-2222-222222222222';
    v_social_head_id UUID := '33333333-3333-3333-3333-333333333333';
    v_social_staff_id UUID := '44444444-4444-4444-4444-444444444444';
    v_homelife_head_id UUID := '55555555-5555-5555-5555-555555555555';
    v_homelife_staff_id UUID := '66666666-6666-6666-6666-666666666666';
    v_psych_head_id UUID := '77777777-7777-7777-7777-777777777777';
    v_psych_staff_id UUID := '88888888-8888-8888-8888-888888888888';
    v_medical_head_id UUID := '99999999-9999-9999-9999-999999999999';
    v_medical_staff_id UUID := 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';
BEGIN
    -- Update Super Admin
    UPDATE profiles SET 
        role = 'super_admin',
        title = 'System Administrator',
        unit = NULL
    WHERE id = v_super_admin_id;

    -- Update Center Head  
    UPDATE profiles SET 
        role = 'center_head',
        title = 'Center Director',
        unit = NULL  -- Center head oversees all units
    WHERE id = v_center_head_id;

    -- Update Social Unit
    UPDATE profiles SET 
        role = 'head',
        title = 'Social Worker III',
        unit = 'social'
    WHERE id = v_social_head_id;

    UPDATE profiles SET 
        role = 'staff',
        title = 'Social Worker I',
        unit = 'social'
    WHERE id = v_social_staff_id;

    -- Update Homelife Unit
    UPDATE profiles SET 
        role = 'head',
        title = 'Houseparent IV',
        unit = 'homelife'
    WHERE id = v_homelife_head_id;

    UPDATE profiles SET 
        role = 'staff',
        title = 'Houseparent II',
        unit = 'homelife'
    WHERE id = v_homelife_staff_id;

    -- Update Psych Unit
    UPDATE profiles SET 
        role = 'head',
        title = 'Psychologist III',
        unit = 'psych'
    WHERE id = v_psych_head_id;

    UPDATE profiles SET 
        role = 'staff',
        title = 'Psychologist I',
        unit = 'psych'
    WHERE id = v_psych_staff_id;

    -- Update Medical Unit
    UPDATE profiles SET 
        role = 'head',
        title = 'Chief Medical Officer',
        unit = 'medical'
    WHERE id = v_medical_head_id;

    UPDATE profiles SET 
        role = 'staff',
        title = 'Staff Nurse',
        unit = 'medical'
    WHERE id = v_medical_staff_id;

    RAISE NOTICE 'Seed accounts updated with new schema fields';

EXCEPTION
    WHEN others THEN
        RAISE NOTICE 'Error updating seed accounts: %', SQLERRM;
END $$;

-- =============================================================================
-- Add Rehab Unit Staff (new accounts with simplified roles)
-- =============================================================================

DO $$
DECLARE
    v_rehab_head_id UUID := 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';
    v_rehab_staff_id UUID := 'cccccccc-cccc-cccc-cccc-cccccccccccc';
BEGIN
    -- Insert rehab unit users into auth.users
    INSERT INTO auth.users (
        id,
        instance_id,
        email,
        encrypted_password,
        email_confirmed_at,
        raw_app_meta_data,
        raw_user_meta_data,
        created_at,
        updated_at,
        role,
        aud
    ) VALUES
    -- Rehab Head
    (
        v_rehab_head_id,
        '00000000-0000-0000-0000-000000000000',
        'rehabhead@rcfms.local',
        crypt('Test@123456', gen_salt('bf')),
        NOW(),
        '{"provider": "email", "providers": ["email"]}',
        '{"full_name": "Dr. Angela Cruz", "role": "head"}',
        NOW(),
        NOW(),
        'authenticated',
        'authenticated'
    ),
    -- Rehab Staff
    (
        v_rehab_staff_id,
        '00000000-0000-0000-0000-000000000000',
        'rehabstaff@rcfms.local',
        crypt('Test@123456', gen_salt('bf')),
        NOW(),
        '{"provider": "email", "providers": ["email"]}',
        '{"full_name": "Physical Therapist Mark Santos", "role": "staff"}',
        NOW(),
        NOW(),
        'authenticated',
        'authenticated'
    )
    ON CONFLICT (id) DO NOTHING;

    -- Update rehab profiles with correct data
    UPDATE profiles SET 
        role = 'head',
        title = 'Rehabilitation Specialist IV',
        unit = 'rehab',
        full_name = 'Dr. Angela Cruz'
    WHERE id = v_rehab_head_id;

    UPDATE profiles SET 
        role = 'staff',
        title = 'Physical Therapist I',
        unit = 'rehab',
        full_name = 'Mark Santos'
    WHERE id = v_rehab_staff_id;

    RAISE NOTICE 'Rehab unit accounts created';

EXCEPTION
    WHEN others THEN
        RAISE NOTICE 'Could not insert rehab users into auth.users: %', SQLERRM;
END $$;

-- =============================================================================
-- TEST ACCOUNTS SUMMARY
-- =============================================================================
-- 
-- Email                       | Password     | Role         | Unit     | Title
-- ----------------------------|--------------|--------------|----------|------------------------
-- superadmin@rcfms.local      | Test@123456  | super_admin  | -        | System Administrator
-- centerhead@rcfms.local      | Test@123456  | center_head  | -        | Center Director
-- socialhead@rcfms.local      | Test@123456  | head         | social   | Social Worker III
-- socialstaff@rcfms.local     | Test@123456  | staff        | social   | Social Worker I
-- homelifehead@rcfms.local    | Test@123456  | head         | homelife | Houseparent IV
-- homelifestaff@rcfms.local   | Test@123456  | staff        | homelife | Houseparent II
-- psychhead@rcfms.local       | Test@123456  | head         | psych    | Psychologist III
-- psychstaff@rcfms.local      | Test@123456  | staff        | psych    | Psychologist I
-- medicalhead@rcfms.local     | Test@123456  | head         | medical  | Chief Medical Officer
-- medicalstaff@rcfms.local    | Test@123456  | staff        | medical  | Staff Nurse
-- rehabhead@rcfms.local       | Test@123456  | head         | rehab    | Rehabilitation Specialist IV
-- rehabstaff@rcfms.local      | Test@123456  | staff        | rehab    | Physical Therapist I
--
-- =============================================================================
